apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp-deployment
  labels:
    app: mongo-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
      - name: mongo-exp-cont
        image: docker.io/mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo.default.svc.cluster.local
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp
spec:
  selector:
    app: mongo-exp
  ports:
  - port: 8081
    targetPort: 8081

